version: '3'

services:

  web:
    container_name: travel
    build: .
    restart: "always"
    env_file: ./.env
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    # links:
    #   - postgres

