version: '3'

services:
  
  web:
    container_name: tenter
    build: .
    restart: "always"
    env_file: ./.env
    volumes:
      - .:/code
    ports:
      - "8079:8000"

    depends_on:
      - "postgres"
